### ISSUE TITLE
Support for DNS TXT record

### ISSUE THREAD

**Issue by dietpiuser** [clempaul/dreamhost-dynamic-dns#15]
Hi, can the script be used to add and remove TXT DNS records using DreamHost API?

**Comment by clempaul** [comment]
Hi @dietpiuser, thanks for the question.

In its current form, this script cannot be used to modify TXT records, however you could modify it to do so (basically update all the places where we specify or look for an A record). 

I'm not quite sure what the use case is here though?

**Comment by dietpiuser** [comment]
I was using TXT record with a current dynamic DNS provider to validate letsencrypt SSL cert. But i've now come across an ACME script that can help with that. So all good here. Thanks.
