### ISSUE TITLE
docs: mention that it requires recent version of bash

### ISSUE THREAD

**Issue by aaronpriven** [clempaul/dreamhost-dynamic-dns#21]
Hi. It looks like something in the trying-multiple-resolvers routine requires a relatively recent version of bash. MacOS comes with bash 3.2 (for license reasons, I believe) and your script doesn't work with that. Installing bash 5.1 fixed the problem. 

I don't think it's at all unreasonable to require a version of bash that's not 15 years old, but I would suggest mentioning that in the documentation. MacOS is a reasonably widely used system... Of course, it's a good idea to upgrade bash anyway, but I hadn't gotten around to doing it on that machine.

I got lost looking at https://wiki.bash-hackers.org/scripting/bashchanges trying to figure it out, so I don't know exactly what version is required.

Thanks for your consideration.

**Comment by clempaul** [comment]
The issue here appears to be that $ENTRY is being split. I can't figure out when this behaviour changed, so figure it's easier to just fix it.

**Comment by clempaul** [comment]
#22 has the fix for this. Thanks for the report @aaronpriven!
