### ISSUE TITLE
Too many current records?

### ISSUE THREAD

**Issue by ggamba** [clempaul/dreamhost-dynamic-dns#9]
Hi, and first of all thank you for this script! Unfortunately, I'm not able to make it work. Maybe it is just my error, but the output looks strange to me. Running it without IP change, I see the following output

```
~/ip-changed$ ./dynamicdns.bash -v
Post process set to: wget
Using API Key: xxxxxxxxxxxxxxxxx
Updating RECORD: ecsoft2.org
No IP Address provided, obtaining public IP
Found current public IP: 151.20.1.207
Current Record: ecsoft2.org A 69.163.136.138
ecsoft2.org A 69.163.136.138
ecsoft2.org A 66.33.205.233
ecsoft2.org A 151.20.1.207
ecsoft2.org A 208.113.200.129
ecsoft2.org A 66.33.205.233
error
no_such_valuedynamicdns.bash Unable to Remove Existing Record
error
record_already_exists_remove_firstdynamicdns.bash Failed to add new record
```

Current public IP is correctly found, but why there are so many "current record" found? Is it correct? Running with "-l" looks right:

~/ip-changed$ ./dynamicdns.bash -v -l
Post process set to: wget
Using API Key: xxxxxxxxxxxxxxxxx
Updating RECORD: ecsoft2.org
No IP Address provided, obtaining public IP
Found current public IP: 151.20.1.207
Found current record: 151.20.1.207

Thanks for any hint!

**Comment by clempaul** [comment]
Thanks for reporting this, sorry for the slow response!

There is indeed an issue with the script where if there are multiple records returned from the Dreamhost API we don't handle it properly (we expect there to be a single result). I'm not really sure the best way to handle this kind of situation - we could either try and delete all of the records or just the first one, but I'm not sure either of these are really the right thing to do (I don't think it actually makes sense to use this script if you would want a record to resolve to multiple places as we can't tell which record came from this particular machine and there are definitely use cases for having multiple entries).

That said, is this still an issue for you? It looks like you only have a single DNS record now, so I think things should be working (maybe you did some manual intervention?).

```
$ dig ecsoft2.org

; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>> ecsoft2.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43172
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ecsoft2.org.                   IN      A

;; ANSWER SECTION:
ecsoft2.org.            14389   IN      A       151.21.194.64

;; Query time: 14 msec
;; SERVER: 194.168.4.100#53(194.168.4.100)
;; WHEN: Sun Nov 03 18:12:56 GMT 2019
;; MSG SIZE  rcvd: 56
```

**Comment by ggamba** [comment]
Hi Paul,

thanks for your reply! I still have the "problem" but I think I've understood why it is happening. I've a web server on ecsoft2.org, and www.ecsoft2.org is a CNAME for ecsoft2.org, so my web server listens to both ecsoft2.org and www.ecsoft2.org and that's all what I need. 

The "problem" is that the web server name is the same as the domain name, and Dreamhost provides several other services for that domain, like:

mail | A | 208.113.200.129
mailboxes | A | 66.33.205.233
webmail | A | 69.163.136.138

All those multiple records that I did not expect are in fact listed under the section "Non-editable DreamHost DNS records", with explanation "These records were added automatically by DreamHost to provide services (such as web hosting or mail) which are active for this domain".

I doubt that you can solve this situation in the script. I should just change the A name from ecsoft2.org to www.ecsoft2.org and then call www.ecsoft2.org from the script - but then I would not be able to add ecsof2.org as CNAME...

**Comment by ggamba** [comment]
I can't say if the suggest modification breaks something else, but robotjohn's solution fixed my problem!
